//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//Msimango KSI
namespace MyEmployee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please Enter RSA ID for Identification")]
        [Display(Name = "RSA ID")]
        [StringLength(13, ErrorMessage = "ID cannot have more than 13 characters")]
        public string ID_Number { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "Your first is required")]
        public string Name { get; set; }
        [DisplayName("Surname")]
        [Required(ErrorMessage = "your surname is required")]
        public string Surname { get; set; }
        [DisplayName("Phone Number")]
      
        [StringLength(10)]
        [DataType(DataType.PhoneNumber)]
        [Range(0, 9999999999, ErrorMessage = "Only 10 numbers allowed")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Only number allowed")]
        public string Contact_Number { get; set; }
        public Nullable<bool> IsActive { get; set; }
        [DisplayName("Date Created")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Created_Date { get; set; }
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
        ErrorMessage = "Email is is not valid.")]
        public string Email { get; set; }
        [DisplayName("Role Name")]
        public Nullable<int> Role_ID { get; set; }
        [DisplayName("Salary")]
        [Required(ErrorMessage = "Salary is required")]
        public Nullable<decimal> Salary { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }
        [DisplayName("Province")]
        [Required(ErrorMessage = "Province is required")]

        public string Province { get; set; }
      
        public virtual Role Role { get; set; }
    }
}
