//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public string RegID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
   
        public virtual Register Register2 { get; set; }
    }
}
